### ISSUE TITLE
handle snake url that ends with /

### ISSUE THREAD

**Issue by dlsteuer** [StemboltHQ/battle_snake#18]
If a snake url ends with a `/` then the server generates a post to `//start` or `//move`. I think the server should be able to handle a trailing slash on the snake url.

**Comment by Dkendal** [comment]
Thanks @dlsteuer, I'll take a look into this today.

**Comment by Dkendal** [comment]
So after thinking about this for a while I've decided this is not something I'm going to support for a couple of reasons.

- cannot account for all user input
- `http://example.com//move` is considered a valid URI
- any reasonable web server should be capable of routing a URI that has extraneous forward slashes.
