### ISSUE TITLE
Connecting to localhost from container

### ISSUE THREAD

**Issue by andreirtaylor** [StemboltHQ/battle_snake#30]
You cant use localhost as a your AI url if you are running the game server from the docker container. The container thinks you are trying to run on its internal localhost and obviously there is nothing running there. Took me a few minutes to realise this when I tried to run my snake.

Might be good to make a note saying to connect to your IP address instead.

**Comment by Dkendal** [comment]
Thanks @andreirtaylor that's a good point, I'll add a note the the docker instructions.

**Comment by andreirtaylor** [comment]
Thanks DK
