### ISSUE TITLE
Unexpected crash occurring when a game is run for a prolonged period of time.

### ISSUE THREAD

**Issue by SynthesizedSoul** [StemboltHQ/battle_snake#52]
Seems to occur after a large amount of turns has occurred. First occurred at ~400 turns, then on second run ~250 turns.

I notice that my Battlesnake (written in Python) also freezes when this occurs, ctrl+c also won't kill the process. I'm unable to diagnose if it's an issue with my Battlesnake.

> [error] GenServer {BattleSnake.GameServer.Registry, "10c217c4-07e4-4565-b4b4-4218af154efd"} terminating
** (stop) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
    (elixir) lib/task/supervised.ex:209: Task.Supervised.stream_reduce/10
    (elixir) lib/stream.ex:1072: Stream.do_zip_next_tuple/5
    (elixir) lib/stream.ex:1049: Stream.do_zip/3
    (elixir) lib/stream.ex:1403: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:1767: Enum.reverse/2
    (elixir) lib/enum.ex:2528: Enum.to_list/1
    (battle_snake) lib/battle_snake/world/move.ex:62: BattleSnake.World.Move.next/1
    (battle_snake) lib/battle_snake/world.ex:116: BattleSnake.World.step/1
    (elixir) lib/map.ex:646: Map.update!/3
    (battle_snake) lib/battle_snake/game_server/state.ex:119: BattleSnake.GameServer.State.step/1
    (battle_snake) lib/battle_snake/game_server/server.ex:108: BattleSnake.GameServer.Server.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :tick

**Comment by Dkendal** [comment]
Thanks @SynthesizedSoul, i'll look into this today!

**Comment by SynthesizedSoul** [comment]
@Dkendal Some further insight, it looks like it doesn't require the server to run for extended periods of time. It also looks like the issue may originate from my battlesnake client code; however, the server locks up (as in the snake stops moving) so it appears that some error handling may be needed regardless. I'm trying to get some reproduction steps. I'll keep this updated with any additional information I can find.

**Comment by SynthesizedSoul** [comment]
@Dkendal Sorry for the quick follow ups, it looks like it may be related to the server being unable to handle not receiving a response.

I created an infinite for loop at the top of my `move()` block, and was able to produce the same error as above.

It's odd though, I placed some print statements at the beginning and end of every major method in my program and they all print out prior to the server not responding --- and the server is showing that my responses on average are 5~8ms.

Hope that helps a little.

**Comment by Dkendal** [comment]
No apology required, I appreciate the feedback. 

Would you be able to confirm that you're using the most recent version of the project build?

About a week ago there was a known issue where no timeout was enforced on client api interaction, so in the event that a client failed to respond that process that was supervising [(OTP lingo)](http://erlang.org/doc/man/supervisor.html) the individual requests reached it's timeout of 5000ms, causing it, all of it's child proceses, and the linked game server process to terminate, which is characteristic of what you're reporting above.

**Comment by SynthesizedSoul** [comment]
I was using a severely outdated version. Thanks for the heads up, I was under the impression Docker kept it up-to-date but that's not the case. Good to know!

Any thoughts on this?:

> [info] Response from POST http://192.168.0.10:8080/move in 7ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 4ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 12ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 9ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 9ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 5ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 3ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 8000ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :connect_timeout}, []}}
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 201ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :timeout}, []}}
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 201ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :timeout}, []}}
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 1002ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :econnrefused}, []}}

It appears to be running normally, and then suddenly there's a massive degradation in performance. I don't believe it's my snake, as the calculations should always roughly take the "same amount of time". If you think it's definitely client related, I'm more than happy for this issue to be closed and I'll evaluate my code further.

**Comment by Dkendal** [comment]
I think in this case it appears to be one of the connected snakes is taking a *very* long time to respond.

The way to read these logs is that many of the `[debug]` entries show how long clients take, or any client issues.

```elixir
# snake at 192.168.0.10:8008 fails to respond here before the timeout is exceeded
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 8000ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :connect_timeout}, []}}

# HTTP connection was refused by snake
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 1002ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :econnrefused}, []}}
```

**Comment by Dkendal** [comment]
It looks like your snake responds on average in ~5ms, and then hits a case where it takes a long time causing it to time out.

**Comment by SynthesizedSoul** [comment]
@Dkendal Sorry for the late reply. I'm a bit concerned about this because I just stripped my move method down to this:

```
CURRENT_INDEX = 0

@bottle.post('/move')
def move():
    global CURRENT_INDEX
    """Handles Battlesnake server move request"""
    data = bottle.request.json

    moves = ['up', 'left', 'down', 'right']
    new_move = moves[CURRENT_INDEX]
    CURRENT_INDEX = (CURRENT_INDEX + 1) % 4

    return {
        'move': new_move,
        'taunt': 'battlesnake-python!'
    }
```

So the only movement it is doing can be calculated in O(1) time.
And I'm still seeing this:

> [info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 4ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 10ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 2ms
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 8001ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :connect_timeout}, []}}
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 201ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :timeout}, []}}
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 202ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :timeout}, []}}
[info] POST http://192.168.0.10:8080/move
[info] Response from POST http://192.168.0.10:8080/move in 1001ms
[debug] [http://192.168.0.10:8080] failed to respond to /move
{:shutdown, {%HTTPoison.Error{id: nil, reason: :econnrefused}, []}}

Could it be bottle that's the issue? Both local and Heroku exhibit this issue. If you're confident it's client-side still, I'll move this issue to the python repo for Battlesnake. Thanks!

**Comment by SynthesizedSoul** [comment]
Adding more information: Using `curl` to POST data to the Battlesnake client lets me do it seemingly indefinitely without fail --- I've let it run for 5 minutes without it failing multiple times now [with many more `/move` requests than the Battlesnake server sends out]. I'm completely stumped now because in my eyes that would imply an issue with the server; but, honestly it could be anything at this point.

I realize you've got so much on your plate with the server as it is; and I'm thankful for any input you can give.

**Comment by Dkendal** [comment]
So to make sure I understand this correctly: 
- running the battle snake server locally in docker
- snake running locally (or heroku)
- curls to your snake do not timeout
- after ~500 turns the server starts to report several timeouts and and eventually that the connection is refused

What do you have your timeout set to in the game server?

I've been monitoring a number of  other snakes and games, and this is the first type of this kind of behavior i've heard of.

From what I understand bottle runs in a single thread by default, so perhaps you're running into some issue where it's still blocking from the last turn.
https://bottlepy.org/docs/dev/async.html#the-limits-of-synchronous-wsgi

I would suggest taking a wallclock measurement from when your snake first receives the move request and when it responds to get a better idea of how long your snake is actually taking to respond.

**Comment by Dkendal** [comment]
Would you be able to include any debugging output from your snake server as well (if it includes response times)

**Comment by SynthesizedSoul** [comment]
Quick update on this: I wound up migrating from Bottle to Flask (same issue appeared) and then finally over to Django. The Django version seems to work perfectly fine with all the code I had written for the Bottle/Flask version. I don't know what's going on; but, it appears to be related to the example snake I started with, probably one of the dependencies. I'm going to go ahead and close this now. I appreciate your patience!

**Comment by Dkendal** [comment]
Not a problem, good luck tomorrow!
