### ISSUE TITLE
Food is Places in a Diagonal Line

### ISSUE THREAD

**Issue by andreirtaylor** [StemboltHQ/battle_snake#61]
As of the latest commit food is always placed on a diagonal line from the top left to the bottom right.

**Comment by andreirtaylor** [comment]
I reverted back to 22c90bd168d0f2e176907c0608dfeb12d5a3942a and it doesnt have the same problem.

**Comment by Dkendal** [comment]
hmm interesting i'll look into this

**Comment by Dkendal** [comment]
Yea you're completely right, i'll try to address this today.
