### ISSUE TITLE
Reason for death does not use snake name 

### ISSUE THREAD

**Issue by andreirtaylor** [StemboltHQ/battle_snake#62]
I get the messages and it states the correct reason for death but it uses a hash as the name instead of the snakes name 

i.e 
Died on turn 182
Collided with 9b6eb7b0-38de-4a31-8888-2d713d88ed24's body

Died on turn 68
Consumed by 667d4471-d6b0-4f35-a113-d8777e019e73

**Comment by Dkendal** [comment]
Thanks @andreirtaylor, I'm currently working on this.

**Comment by Dkendal** [comment]
Closed by #70
