### ISSUE TITLE
custom heads/tails don't seem to be working

### ISSUE THREAD

**Issue by dlsteuer** [StemboltHQ/battle_snake#72]
I've pulled the latest docker image, and sent the following json for game start `{"color":"#35AA47","head_url":"https://s3.amazonaws.com/john-box-o-mysteries/swu-logo.png","name":"dsnek","head_type":"dead","tail_type":"fat-rattle"}` and my snake is still using the default head and tail

**Comment by Dkendal** [comment]
fixed by 5aab36e3456c0a784b342972a19008dab5d092bd
