### ISSUE TITLE
Long taunts can cause the UI to break a bit

### ISSUE THREAD

**Issue by JemBijoux** [StemboltHQ/battle_snake#73]
![screenshot 2017-03-02 09 06 05](https://cloud.githubusercontent.com/assets/8083892/23520801/46806290-ff31-11e6-9538-058d75b806d7.png)

See screenshot. It might be nice to throw an overflow hidden on there? It would also be good to know if you were to cut it off for some reason. (I had this idea that I'd pass data back to my snake using the taunt, but having that blob of data in the UI might look gross.)

Also: I'm pretty sure someone else will think about abusing this day of.

**Comment by Dkendal** [comment]
Will definitely add an overflow. Can't really do any sort of text too long warnings though because the screen size is variable

**Comment by JemBijoux** [comment]
Yeah, fine with no warnings. Ultimately it doesn't matter how it's displayed so long as a long taunt doesn't cause the rest of the interface to break. An overflow:hidden/max-width is the easy fix.

I noticed there was another bug logged (https://github.com/StemboltHQ/battle_snake/issues/50) for taunts updating through out the course of the game. Is it safe to assume that once that is fixed, your previous taunt will always be submitted as part of the json request to `/move`? (It would open up some interesting opportunities to pass data among snakes via the taunt.)

**Comment by Dkendal** [comment]
That is correct
